# Generated by Django 3.2.5 on 2021-07-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id_parse_page', models.AutoField(primary_key=True, serialize=False)),
                ('json_res', models.TextField()),
            ],
        ),
    ]
